// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/worker/sshserver (interfaces: Authorizer)
//
// Generated by this command:
//
//	mockgen -package mocks -destination worker/sshserver/mocks/authorizer_mock.go github.com/juju/juju/worker/sshserver Authorizer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	names "github.com/juju/names/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthorizer is a mock of Authorizer interface.
type MockAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizerMockRecorder
}

// MockAuthorizerMockRecorder is the mock recorder for MockAuthorizer.
type MockAuthorizerMockRecorder struct {
	mock *MockAuthorizer
}

// NewMockAuthorizer creates a new mock instance.
func NewMockAuthorizer(ctrl *gomock.Controller) *MockAuthorizer {
	mock := &MockAuthorizer{ctrl: ctrl}
	mock.recorder = &MockAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizer) EXPECT() *MockAuthorizerMockRecorder {
	return m.recorder
}

// AuthorizedKeysPerUser mocks base method.
func (m *MockAuthorizer) AuthorizedKeysPerUser(arg0 names.UserTag) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorizedKeysPerUser", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthorizedKeysPerUser indicates an expected call of AuthorizedKeysPerUser.
func (mr *MockAuthorizerMockRecorder) AuthorizedKeysPerUser(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizedKeysPerUser", reflect.TypeOf((*MockAuthorizer)(nil).AuthorizedKeysPerUser), arg0)
}
